### ISSUE TITLE
the comfyUI custom_node that recommended was not able to work well

### ISSUE THREAD

**Issue by dwgeneral** [TMElyralab/MuseTalk#61]
1. firstly, the min support cuda version is 11.8, otherwise, you will got device image is invalid error
2. the custom_node ComfyUI-MuseTalk has leak GPU memory issue, when we run other workflows after installed it, we might get `torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)` issue, once we remove the ComfyUI-MuseTalk folder from custom_nodes, the issue was gone.
3. pls keep to update to make it work well if you recommended it

**Comment by DeepAichemist** [comment]
You might want to check out these two articles：https://blog.csdn.net/debug_ding/article/details/138712598?spm=1001.2014.3001.5501        https://blog.csdn.net/debug_ding/article/details/138845805?spm=1001.2014.3001.5501

**Comment by AIFSH** [comment]
https://github.com/AIFSH/ComfyUI-MuseTalk_FSH
fix OOM,you may try

**Comment by czk32611** [comment]
> 1. firstly, the min support cuda version is 11.8, otherwise, you will got device image is invalid error
> 2. the custom_node ComfyUI-MuseTalk has leak GPU memory issue, when we run other workflows after installed it, we might get `torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)` issue, once we remove the ComfyUI-MuseTalk folder from custom_nodes, the issue was gone.
> 3. pls keep to update to make it work well if you recommended it

Sorry to let you know that we don't have enough energy to maintain comfyUI. The one we recommend is from a third party. It would be better if you leave an issue there.

We will recomment a new one if we found something better.
